Ghostnet
OjusWiZard/ctez pull request #1
Opened 2023-01-10 07:32 UTC by TarunWebdev

2023-01-17 06:02 UTC, OjusWiZard requested changes
Could you add a comment link to the code line on GitHub, wherever you took the reference for the logic?

2023-01-17 06:02 UTC, OjusWiZard commented on frontend/app/src/api/contracts.ts
> +  fee = (Math.abs(outstanding - 8*cashPool)*(2**22))/outstanding;
This should be in else block, right?

2023-01-17 06:02 UTC, OjusWiZard commented on frontend/app/src/api/contracts.ts
> +  const annual_fee = Math.exp(new_fee_index / ((2**48) * 365.25 * 24 * 3600));
Arthur said it to be fee_r instead of new_fee_index. Can you please check that once?

2023-01-17 06:02 UTC, OjusWiZard commented on frontend/app/src/components/Trade/Swap/Swap.tsx
> +    : e_rate = (trade_dcash_for_dtez({tez:cashPool.toNumber() , cash:tokenPool.toNumber() , dtez: 1000000 , target , rounds: 4})*9999/10000)/1e6
I think we are passing incorrect values in the above two lines.
`dtez` is hardcoded instead of `SwapAmount`.
And both `trade_dtez_for_dcash` and `trade_dcash_for_dtez` are having the same arguments...
Some other argument also seem wrong, please cross check them once from [here](https://github.com/OjusWiZard/ctez/blob/fees/cfmm_tez_ctez.mligo#L327) and [here](https://github.com/OjusWiZard/ctez/blob/fees/cfmm_tez_ctez.mligo#L365)

2023-01-17 06:02 UTC, OjusWiZard commented on frontend/app/src/components/sidebar/Sidebar.tsx
> +  return formatNumberStandard(e_rate);
Please add a separate utility file for this redundant code.

2023-01-18 05:10 UTC, TarunWebdev commented on frontend/app/src/api/contracts.ts
> +  fee = (Math.abs(outstanding - 8*cashPool)*(2**22))/outstanding;
yes I missed that in last commit, it was above the if else block before, fixed it

2023-01-18 05:22 UTC, TarunWebdev commented on frontend/app/src/api/contracts.ts
> +  const annual_fee = Math.exp(new_fee_index / ((2**48) * 365.25 * 24 * 3600));
umm, can you add me to the group chat with Arthur and Om? Ig it'll be new_fee_index only. As fee_r is a constant value and new_fee_index is updating the value with current ctez value in cfmm

2023-01-18 05:24 UTC, TarunWebdev commented on frontend/app/src/components/Trade/Swap/Swap.tsx
> +    : e_rate = (trade_dcash_for_dtez({tez:cashPool.toNumber() , cash:tokenPool.toNumber() , dtez: 1000000 , target , rounds: 4})*9999/10000)/1e6
umm no, It's for calculating the price on 1 ctez to tez and 1 tez to ctez, that's whu dtez = 100000. I'll write it in cleaner way

2023-01-23 12:09 UTC, OjusWiZard commented on frontend/app/src/components/Trade/Swap/Swap.tsx
> +    : e_rate = (trade_dcash_for_dtez({tez:cashPool.toNumber() , cash:tokenPool.toNumber() , dtez: 1000000 , target , rounds: 4})*9999/10000)/1e6
Ah, got it!

2023-02-07 21:03 UTC, OjusWiZard approved these changes

2023-02-07 21:03 UTC, merged